version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./ci/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    container_name: vite-vue3-starter
    ports:
      - '3000:80'
